# Generated by Django 5.1.4 on 2025-01-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_preparation_steps'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Categoty',
            new_name='Category',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cover',
            field=models.ImageField(blank=True, default='', upload_to='recipes/covers/%Y/%m/%d/'),
        ),
    ]
